AWSTemplateFormatVersion: '2010-09-09'

Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0532be01f26a3de55   # Amazon Linux (change region if needed)
      InstanceType: t3.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
